config/routes.rb
Rails.application.routes.draw do
  get 'bookmarks/new'
  get 'lists/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get 'lists', to: 'lists#index'
  root 'lists#index'
  get 'lists/new', to: 'lists#new'
  post 'lists', to: 'lists#create'
  get 'lists/:id', to: 'lists#show', as: :list
  get "lists/:list_id/bookmarks/new", to: 'bookmarks#new', as: :new_list_bookmark
  post "lists/:list_id/bookmarks", to: 'bookmarks#create', as: :list_bookmarks
  get "lists/:list_id/bookmarks", to: 'bookmarks#index'
  delete 'bookmarks/:id', to: 'bookmarks#destroy', as: :delete_bookmark
  post 'lists/:list_id/reviews', to: 'reviews#create', as: :list_reviews
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie, dependent: :destroy
  belongs_to :list
  # Un commentaire doit faire au moins 6 caractères
  validates :comment, length: { minimum: 6 }
  # Pour valider qu'un signet (Bookmark) est unique pour un couple donné de film (Movie) et de liste (List),
  # on utilise la validation uniqueness avec une portée (scope) spécifique.
  validates :list_id, uniqueness: { scope: :movie_id, message: "est déjà associé à ce film dans la liste" }
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :photo

  has_many :bookmarks, dependent: :destroy
  # On lie la table à movie (liaison many to many)
  has_many :movies, through: :bookmarks
  # On lie la table à review
  has_many :reviews, dependent: :destroy
  # une liste doit avoir un nom, et pas de blanc
  validates :name, uniqueness: true, presence: true, allow_blank: false
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  # # On lie la table à list (liaison many to many)
  has_many :lists, through: :bookmarks
  # Le titre est obligatoire, et unique
  validates :title, presence: true, uniqueness: true
  # L'overview obligatoire
  validates :overview, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :list
  validates :rating, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    # On récupère l'id de la liste
    @list = List.find(params[:list_id])
    # On instancie le bookmark
    @bookmark = Bookmark.new
  end

  def create
    # On récupère l'id de la liste
    @list = List.find(params[:list_id])
    # Pas besoin de récupérer movie, il le fera dans l'instanciation,
    # On l'a mis dans les strongs params
    ## Non => @movie = Movie.find(bookmark_params[:movie_id])
    @bookmark = Bookmark.new(bookmark_params)
    # On va dire que list_id = list.id, pour qu'il l'enregistre
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      # On affiche le formulaire avec les messages d'erreur,
      # mis dans la validation des données, seront générées avec Simple_form
      render :new, status: :unprocessable_entity
    end
  end

  def index
    @bookmarks = Bookmark.all
  end

  def destroy
    raise
    @bookmark = Bookmark.find(params[:list_id])
    @bookmark.destroy
    redirect_to lists_path, status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)  # Ajoutez :movie_id à la liste des paramètres autorisés
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    # On récupère la liste des films
    @movies = @list.movies
    ## Partie pour le formulaire d'ajout du review
    # On récupère l'id de la liste
    # @list = List.find(params[:id])
    # On instancie la review
    @review = Review.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(set_params_list)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list = List.find(params[id])
    @list.destroy
    redirect_to lists_path, status: :see_other

  end

  private

  def set_params_list
    params.require(:list).permit(:name, :photo)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @review = Review.new(review_params)
    # On a besoin de récupérer l'id de la liste
    @list = List.find(params[:list_id])
    # On va mettre la valeur de l'id de la liste dans l'instance
    @review.list = @list
    if @review.save
      redirect_to list_path(@list)
    else
      render "lists/show", status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:comment, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/bookmarks/index.html.erb
<div class="container mt-4">
  <h1>Liste des bookmarks</h1>
  <div class="row">
      <% @bookmarks.each do |bookmark| %>
      <div class="col-md-4">
        <div class="card-trip">
          <img src="<%= bookmark.movie.poster_url %>" />
          <div class="card-trip-infos">
            <div>
              <h2><%= bookmark.movie.title %></h2>
              <p><%= bookmark.movie.overview %></p>
            </div>
            <h2 class="card-trip-pricing"><%= bookmark.comment %></h2>
          </div>
        </div>
        <%= bookmark.list.name %>
      </div>
      <% end %>
  </div>
</div>

app/views/bookmarks/new.html.erb
<div class="banner">
  <div class="container">
    <h1><%= @list.name %></h1>
  </div>
</div>
<div class="container mt-4">
  <div>
    <%= link_to lists_path, class: "btn-accueil" do %>
      <i class="fas fa-home"></i>
    <% end %>
  </div>
  <h1>Add Your bookmark</h1>
  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.input :comment %>
    <%= f.association :movie, collection: Movie.all, prompt: "Select a movie" %>
    <%= f.submit "Add Bookmark", class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
      <div class="container-fluid">
        <a class="navbar-brand" href="lists">
          <%= image_tag "logo.png", alt: "Logo Watch List", width: 100 %>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto">
              <li class="nav-item active">
                <%= link_to "My lists", lists_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "New list", lists_new_path, class: "nav-link" %>
              </li>
          </ul>
        </div>
      </div>
    </div>

    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="banner">
  <div class="container">
    <h1>Save any kind of movies</h1>
    <p>Classic</p>
  </div>
</div>
<div class="container mt-5">
  <h1>My lists</h1>
    <%= link_to "Create a movie list", lists_new_path, class: "btn btn-flat float-end" %>

  <div class="row">
    <% @lists.each do |list| %>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= list.photo.attached? ? cl_image_path(list.photo.key) : "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg" %>)">
      <%= link_to list.name, list_path(list) %>
    </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="banner">
  <div class="container">
    <h1>Classic movies</h1>
  </div>
</div>
<div class="container mt-4">
  <h1>Ajout d'une liste</h1>
	<%= simple_form_for(@list) do |f| %>
	  <%= f.input :name %>
    <%= f.input :photo, as: :file %>
	  <%= f.submit "Add a list", class: 'btn btn-primary' %>
  <% end %>
  <%= link_to lists_path, class: "btn-accueil" do %>
    <i class="fas fa-home"></i>
  <% end %>
</div>

app/views/lists/show.html copy.erb
<div class="banner">
  <div class="container">
    <h1><%= @list.name %></h1>
  </div>
</div>
<div class="container mt-4">
  <div class="card">
    <p class="card-title"><%= @list.name %></p>

    <%= link_to new_list_bookmark_path(@list), class: "bookmark" do %>
      <i class="fas fa-plus-circle"></i>
    <% end %>
  </div>

  <%= link_to lists_path, class: "btn-accueil" do %>
    <i class="fas fa-home"></i>
  <% end %>
</div>

app/views/lists/show.html.erb
<div class="banner">
  <div class="container">
    <h1><%= @list.name %></h1>
  </div>
</div>
<div class="container mt-4">
  <div class="row">
    <div class="d-flex justify-content-between flex-row my-4">
      <div>
        <%= link_to lists_path, class: "btn-accueil" do %>
          <i class="fas fa-home"></i>
        <% end %>
      </div>
      <div>
        <%= link_to "Add a movie", new_list_bookmark_path(@list), class: "btn btn-primary add_movie"  %>
      </div>
    </div>
    <% @movies.each do |movie| %>
    <div class="col-md-4">
      <div class="card-trip">
          <img src="<%= movie.poster_url %>" />
          <div class="card-trip-infos">
            <div>
              <div class="d-flex justify-content-between">
                <h2><%= movie.title %></h2>
                <div class="d-flex">
                  <h2 class="card-trip-pricing"><%= movie.rating %></h2>
                  <i class="fas fa-star" style="color: #fbdc04;"></i>
                </div>
              </div>
              <p><%= movie.overview %></p>
            </div>
          </div>
      </div>
    </div>
    <% end %>
  </div>
  <hr class="my-5">
</div>

<div class="container mt-4">
  <div class="row d-flex justify-content-between">
    <div class="col-md-4">
      <h1>Reviews</h1>
      <% @list.reviews.each do |review| %>
      <div>
        <% (1..5).each do |i| %>
          <% if i <= review.rating %>
            <i class="fas fa-star star-yellow"></i>
          <% end %>
        <% end %>
        <p class="mb-0">
          <%= review.comment %>
        </p>
      </div>
      <hr class="my-5">
      <% end %>
    </div>
    <div class="col-md-4">
      <div class="card-bookmark">
        <h1>Add Your Review</h1>
        <%= simple_form_for [@list, @review] do |f| %>
          <%= f.input :comment, placeholder: "Add your review here..." %>
          <%= f.input :rating, collection: (1..5).to_a, label: "Rate your experience", input_html: {data: {controller: "star-rating"}} %>
          <%= f.submit "Add Review", class: 'btn btn-primary' %>
        <% end %>
      </div>
    </div>
  </div>
</div>